sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
language: node_js
node_js:
  - "stable"
services:
  - "mysql"
cache:
  directories:
  - node_modules
before_script:
  - cd web
  - npm install
  - npm run start-selenium
  - npm run build-css
  - cd ../server
  - npm install
  - npm run db:dev
  - cd ../mobile
  - npm install
  - cd ..
script:
  - cd web
  - xvfb-run make test
  - xvfb-run test
  - npm test
  - npm run build
  - cd ../mobile
  - npm test
  - cd ../server
  - npm test
  - cd .. 

deploy:
  provider: elasticbeanstalk
  access_key_id: $EBS_ACCESS_KEY
  secret_access_key:
    secure: '$EBS_SECRET_KEY'
  region: "us-east-2"  
  app: "Cinder"
  env: "Cinder-env"
  bucket_name: "elasticbeanstalk-us-east-2-148400404701"
  skip_cleanup: true
  on:
    branch: master
