language: node_js
node_js:
  - "stable"
services:
  - "mysql"
cache:
  directories:
  - node_modules
before_script:
  - cd client && npm install
  - cd ../server && npm install
  - cd ../mobile && npm install
script:
  - cd client
  - npm test
  - npm run build
  - cd ../mobile
  - npm test
